---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  labels:
    app: backend-service
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: order-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-api-deployment
  labels:
    app: backend
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - image: anthonyamanse/order-api:1.0
          name: nodejs-app
          env:
            - name: SLACK_WEBHOOK
              value: ''
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: 50m
